name: Lint

on: [pull_request]

jobs:
  blackify-code:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - run: |
          python -m pip install --upgrade pip
          pip install black[jupyter]==24.3
      - run: black ./Motus

      - name: Get last commit message
        id: last-commit
        run: |
          echo "message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
          echo "author=$(git log -1 --pretty=\"%an <%ae>\")" >> $GITHUB_OUTPUT
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_author: ${{ steps.last-commit.outputs.author }}
            commit_message: ${{ steps.last-commit.outputs.message }} (blackified)
            commit_user_name: BlackifyBot
            commit_options: '--amend --no-edit --allow-empty'
            push_options: '--force'
            skip_fetch: true